sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "12"
  - "10"
  - "8"
before_install:
  - npm i -g npm@6.14.2
script:
  # Unfortunately flow falls over when a dep exists in peer deps and others. :(
  # @see https://github.com/flowtype/flow-typed/issues/528
  #- yarn run flow:defs
  - yarn run test
after_success:
  # Deploy code coverage report to codecov.io
  - yarn run test:coverage:deploy
