name: PR Validate

on:
  pull_request:
    branches:
      - master

jobs:
  code-quality:
    name: Code Quality
    strategy:
      matrix:
        command:
          - lint
          - dtslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - shell: bash
        run: yarn ${{ matrix.command }}

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - shell: bash
        run: yarn test:coverage
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
